### PR TITLE
Allow GIFs in reports

### PR DESCRIPTION
**Pull request by tsalo**
Related to #124.

Changes proposed:

- Add `.gif` to the list of valid extensions.

### CODE REVIEW

**Comment by tsalo** [comment]
I also wanted to double-check that raising an exception for unsupported extensions (which I added in #126) made sense:

https://github.com/nipreps/nireports/blob/dc54385842c370eedaed5b1b5f0cbd9eb5692899/nireports/assembler/reportlet.py#L295-L296

**Review by oesteban — APPROVED** [review]

**Comment by effigies** [comment]
Yes, I'm working on a release cascade. Started with nitransforms, moving onto nipype, and then nireports and niworkflows, and so on.

**Comment by tsalo** [comment]
Awesome!

**Comment by effigies** [comment]
I went ahead and released 24.0.3.

**Pull request merged**
