### PR TITLE
ENH: Higher-level carpetplot tooling for DWI

### PR DESCRIPTION
**Pull request by teresamg**

### CODE REVIEW

**Comment by effigies** [comment]
@teresamg Please `git pull` before continuing work on this PR.

**Comment by jhlegarreta** [comment]
Cross referencing https://github.com/nipreps/eddymotion/pull/192#discussion_r1602060187. Note that the `get_segment_labels` function should probably be carried over to here as well.

**Comment by oesteban** [comment]
@teresamg @arokem what's the status of this? can we try to merge it before tomorrow's meeting? I am happy to push tonight/tomorrow morning -- let me know how I can help.

**Comment by teresamg** [comment]
Right now I think it just needs thorough testing with dwi data + bvals + segmentation... there wasn't much in the tests/data folder but what's there did run without breaking

**Pull request merged**
