### PR TITLE
STYLE: Transition to `ruff` for code formatting

### PR DESCRIPTION
**Pull request by jhlegarreta**
Transition to `ruff` for code formatting in line with the rest of the `nipreps` repositories.

Drop the flake8 `W503` rule, which is not implemented by `ruff`.

Add a GHA workflow to ensure that contributions not complying with the style are detected.

Format the source code accordingly.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
A few notes:
- The `isort`, `black` and `flake8` rules were not being previously enforced anyways :grimacing:.
-  It looks like these lines
   https://github.com/nipreps/eddymotion/blob/main/.github/workflows/contrib.yml#L22-L25
   fix silently the errors:
   https://github.com/nipreps/nireports/actions/runs/9039088266/job/24841362350?pr=114

   I this PR I have changed those lines to
   https://github.com/nipreps/nireports/pull/114/files#diff-254a142c6921a1cfd1e55d3e3070a5ce40a95632c0b3449dc51f0746aa8b6bcaR24
  
  Which is more comprehensive (?), as it runs all pre-commit hooks (not only ruff). Otherwise, we may need to add the `--show-fixes` or `--show-diff-on-failure` flags.

  So the same is probably happening across all `nipreps` repositories :grimacing:.
 
- I would leave out for now the `B019` and `C901` errors: fixing those requires more time.

**Comment by jhlegarreta** [comment]
The exclude rules
https://github.com/nipreps/nireports/pull/114/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9R21-R25 seem not to be working, and `pretty format json` only shows the diff locally...

**Comment by jhlegarreta** [comment]
@effigies @oesteban Should we add `B019` and `C901` to the whitelist until we have time to look at them?

**Comment by effigies** [comment]
@jhlegarreta Yes, let's ignore those for now.

**Pull request merged**
