### PR TITLE
ENH: Add raincloud plot capabilities

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add raincloud plot capabilities and demonstrate on the FA values of computed on a DWI volume across different tissue types.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Re https://github.com/nipreps/mriqc/issues/1216#issuecomment-2053722420

>> FA, MD, residuals [2], etc. mean/stddevs, etc. in e.g. in tissues/across subjects

> Happy to add. For now we only have degenerate FA voxels in ppm.

@oesteban Would need data to finish this: figure out how scalar maps are provided or how the data would be stored as TSV files from upstream processes (`smriprep`, `dmriprep` ?).

**Comment by jhlegarreta** [comment]
`Contribution checks` failures are unrelated:
https://github.com/nipreps/nireports/actions/runs/9149429918/job/25153033558?pr=118#step:4:145

**Comment by jhlegarreta** [comment]
@oesteban Adding more customizations to this can be left for separate PRs. Dealing with the `kwargs` as well (it is uncertain to me how those would be dealt with the [interface](https://github.com/nipreps/nireports/pull/118/files#diff-db0ce3fbc7d260fb491be6c2a2a86c052bacb834a819b04b7bcf7043234a97e1R147)).

**Review by oesteban — APPROVED** [review]

**Comment by jhlegarreta** [comment]
@oesteban I am unsure about the relevance of this now, as I have seen that the group reports that you already have available in `mriqc` are equivalent to these:
https://mriqc.readthedocs.io/en/latest/reports/group.html#group-reports

So if the latter are generated from `nireports`, then this PR is unfortunately not all that interesting. If the are not, maybe those capabilities should be transferred to `nireports` and adopt that style instead of introducing a new one here.

**Comment by oesteban** [comment]
I think this can come handy at some point, I can't see a reason to pull it back now :)

**Pull request merged**
