### PR TITLE
Support PNGs and JPGs in reportlets

### LINKED ISSUE #124: Support PNG and JPEG figures in reports
### What would you like to see added in this software?

With 23.2.1, it doesn't look like PNG figures are collected by Nireports, even when I specify the extension field as `.png` or `png`. If possible, it would be great to support these figures, as QSIRecon has some figures that it can't save as SVGs.

### Do you have any interest in helping implement the feature?

Yes

### Additional information / screenshots

_No response_

### PR DESCRIPTION
**Pull request by tsalo**
Closes #124.

Changes proposed:

- Add a section to embed PNGs and JPGs in the HTML report.
- Raise an exception if an extension isn't supported.

### CODE REVIEW

**Comment by tsalo** [comment]
@effigies if you end up merging this, would you be willing to make a new release (23.2.2?) so QSIRecon can use the modified version?

**Comment by effigies** [comment]
Do you want to rebase onto the maintenance branch? There are a bunch of unrelated changes on `master`.

**Comment by tsalo** [comment]
Can do!

**Comment by tsalo** [comment]
nope i messed it up. i'm just going to open a new PR

**Pull request closed without merging**
