### PR TITLE
FIX: Create setup.py file

### LINKED ISSUE #12: Package can't be installed in editable mode
It will be useful to enable installation with `pip`'s `-e` flag.

### PR DESCRIPTION
**Pull request by ZviBaratz**
Created minimal setup.py file for the package in order to enable installation in editable mode (resolves #12).

### CODE REVIEW

**Comment by effigies** [comment]
I didn't realize that I'd disabled editable installs. Apologies.

**Comment by effigies** [comment]
I'm able to install in editable mode with moderately recent pip without this change:

```
$ pip install -e .
Obtaining file:///home/chris/Projects/nipreps/nireports
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: nibabel>=3.0.1 in /home/chris/miniconda3/envs/nireports-dev/lib/python3.9/site-packages (from nireports==0.1.dev16+g9251ef2) (3.2.2)
Requirement already satisfied: numpy>=1.14 in /home/chris/miniconda3/envs/nireports-dev/lib/python3.9/site-packages (from nibabel>=3.0.1->nireports==0.1.dev16+g9251ef2) (1.22.4)
Requirement already satisfied: setuptools in /home/chris/miniconda3/envs/nireports-dev/lib/python3.9/site-packages (from nibabel>=3.0.1->nireports==0.1.dev16+g9251ef2) (61.2.0)
Requirement already satisfied: packaging>=14.3 in /home/chris/miniconda3/envs/nireports-dev/lib/python3.9/site-packages (from nibabel>=3.0.1->nireports==0.1.dev16+g9251ef2) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/chris/miniconda3/envs/nireports-dev/lib/python3.9/site-packages (from packaging>=14.3->nibabel>=3.0.1->nireports==0.1.dev16+g9251ef2) (3.0.9)
Installing collected packages: nireports
  Running setup.py develop for nireports
Successfully installed nireports-0.1.dev16+g9251ef2
$ ls
nireports  nireports.egg-info  LICENSE  min-requirements.txt  pyproject.toml  README.md  setup.cfg
$ pip --version
pip 21.2.4 from /home/chris/miniconda3/envs/nireports-dev/lib/python3.9/site-packages/pip (python 3.9)
```

**Comment by ZviBaratz** [comment]
Oh, that's new - I was using 20.0.2 and it failed. 
Mazal tov to Python packaging :tada:

**Comment by effigies** [comment]
Yeah, things are moving fast. It's a pain to keep up, but getting to be even more of a pain to support the whole spread of possible configurations. TBH I'm okay with re-adding `setup.py` just to keep things from breaking for people who haven't thought to update pip. Or we could put `pip install --upgrade pip` into our installation instructions (which don't exist yet).

**Comment by effigies** [comment]
FWIW I opened a thread on discuss.python.org to see what people consider best practices: https://discuss.python.org/t/best-practices-for-supporting-installation-through-ranges-of-pip-versions/16471

**Comment by ZviBaratz** [comment]
Thank you! 
I have to admit I really like the thought of getting rid of the `setup.py` altogether and simply including a pip upgrade in the installation instructions. In any case, I'd be happy to reopen this if you prefer. We can also wait to see if anyone has any intereseting thoughts on the discuss.python.org thread.

**Pull request closed without merging**
