### PR TITLE
MAINT: Created contribution guidelines

### LINKED ISSUE #18: Create contribution guidelines
The repo is missing a reference to nipreps contribution guidelines.

### PR DESCRIPTION
**Pull request by ZviBaratz**
Copied [fMRIPre's contribution guidelines](https://github.com/nipreps/fmriprep/blob/master/CONTRIBUTING.md) template to link to the nipreps project's address (resolves #18).

### CODE REVIEW

**Comment by ZviBaratz** [comment]
Just realized it also exists [under the .github repo](https://github.com/nipreps/.github/blob/main/.github/CONTRIBUTING.md). 
@effigies / @oesteban is that supported yet? I don't see a link in GitHub's top-right repo summary on the main page (like the code of conduct has).

**Comment by oesteban** [comment]
> Just realized it also exists [under the .github repo](https://github.com/nipreps/.github/blob/main/.github/CONTRIBUTING.md). @effigies / @oesteban is that supported yet? I don't see a link in GitHub's top-right repo summary on the main page (like the code of conduct has).

It does work. There's a link under the About section on the right-hand side of the repo's home page.

**Comment by ZviBaratz** [comment]
This is strange, I don't seem to have it:
image
(am I missing something? I feel like I must be, but I really don't see anything)

In any case, sounds like it's somehow a local issue. I'll go ahead and close this.

**Comment by oesteban** [comment]
Sorry, you are right - I thought you were talking about the code of conduct.

Contributing guidelines should be supported too (https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file), but it doesn't seem to show up anywhere.

I think it is reasonable to open and merge your PR - apologies for the confusion again.

**Pull request merged**
