### PR TITLE
ENH: Add DWI volume plot method

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add DWI volume plot method.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Test data missing in here: tested with ds000114 from openneuro. Probably too large (104 MB) to add it here. Let me know which other dMRI volume that you know we could use.

**Comment by effigies** [comment]
Added a downsampled and truncated copy of the indicated file. 3.5MB, which seems a reasonably modest addition and will be excluded from wheels.

**Comment by jhlegarreta** [comment]
> Added a downsampled and truncated copy of the indicated file. 3.5MB, which seems a reasonably modest addition and will be excluded from wheels.

Thanks for working on this Chris :100:. The bvals and bvecs have not been truncated, though and even if the test is passing, the gradient direction may not correspond to the one that is displayed.

IMO best would be to rename the test files (including the DWI image) to clearly state that they have been truncated and to reduce confusion with the original image on OpenNeuro.

Can you please do this @effigies ?

**Comment by jhlegarreta** [comment]
Thanks Chris. Merging.

**Pull request merged**
